#!/usr/bin/env bash
# in order to run a script it must be made executable
# using filter you are able to run a specific script

sudoTest() {

  SUDOTEST=$(sudo id -u)

  if [ $(id -u) -ne 0 ]; then
    echo "This script must be run with sudo." >&2
    exit
  fi

}
sudoTest

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"

cd $script_dir
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f)

while [[ $# > 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "run: filter=$filter"

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtered: $filter -- $script"
    continue
  fi
  log "running script: $script"
  execute ./$script
done
