#!/usr/bin/env bash

## in order to run a script it must be made executable
## using filter you are able to run a specific script

# Ensures the script is not running as sudo or root

CURRENTUSER=$(whoami)

if [[ $CURRENTUSER == "root" ]]; then
  echo "Do not run this script as root/sudo"
  exit
fi

# attempts to gain sudo access if not already accquired

sudo -v

# exits the script if sudo access is not granted
sudo -n true 2>/dev/null || {
  echo "You must have the ability to run sudo commands to execute this script"
  exit 1
}

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter=""
dry="0"

# source the .env file prior to running any functions
source "$script_dir/.env"

cd $script_dir
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f | sort)

while [[ $# > 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "run: filter=$filter"

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtered: $filter -- $script"
    continue
  fi
  log "running script: $script"
  execute ./$script
done
