#!/usr/bin/env bash

sudo -v
timedatectl set-ntp false
sudo -v
timedatectl set-timezone "America/Toronto"
sudo -v
timedatectl set-ntp true
sudo -v
sudo timedatectl set-local-rtc 0 --adjust-system-clock
sudo -v
