#!/usr/bin/env bash
set -x

[[ "$XDG_CURRENT_DESKTOP" == "GNOME" ]] || exit

sudo apt install libglib2.0-dev-bin gnome-tweaks gnome-themes-extra gtk2-engines-murrine sassc gnome-shell-extensions

GRAPHITE="Graphite-gtk-theme"
TELA_ICONS="Tela-circle-icon-theme"

## dl theming
git clone "https://github.com/vinceliuice/$GRAPHITE" "/tmp/$GRAPHITE"
git clone "https://github.com/vinceliuice/$TELA_ICONS" "/tmp/$TELA_ICONS"

## execute themeing
### icons
pushd "/tmp/$TELA_ICONS" || exit

./install.sh black grey

popd || return
rm -rf "/tmp/$TELA_ICONS"

### graphite
pushd "/tmp/$GRAPHITE" || exit

./wallpaper/install-wallpapers.sh --theme standard --system default debian

./install.sh
./install.sh -l
sudo ./install.sh -g

popd || return
rm -rf "/tmp/$GRAPHITE"

# change gnome settings
PROFILE_ID=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')

gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface gtk-theme 'Graphite'
gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-black-light'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.background picture-uri file:///home/debian/.local/share/backgrounds/wave-Light.jpg
gsettings set org.gnome.desktop.background picture-uri-dark file:///home/debian/.local/share/backgrounds/wave-Dark.jpg

gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/" font "'JetBrainsMonoNL Nerd Font Mono 13'"
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE_ID/" cell-width-scale 1.05
# gsettings set org.gnome.desktop.interface accent-color 'slate'

# cd into icon dir and run ./install.sh -c black grey
# gtk-engine-murrine on Arch Linux
# gtk-murrine-engine on Fedora
# gtk2-engine-murrine on openSUSE
# gtk2-engines-murrine on Debian, Ubuntu, etc.
