#!/usr/bin/env bash

# Ensures the script is not running as sudo or root

CURRENTUSER=$(whoami)

if [[ $CURRENTUSER == "root" ]]; then
  echo "Do not run this script as root/sudo"
  exit
fi

# attempts to gain sudo access if not already accquired

sudo -v

# exits the script if sudo access is not granted
sudo -n true 2>/dev/null || {
  echo "You must have the ability to run sudo commands to execute this script"
  exit 1
}

# install c build tools
# install nerd font
wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip &&
  cd ~/.local/share/fonts &&
  unzip JetBrainsMono.zip &&
  rm JetBrainsMono.zip &&
  fc-cache -fv


