#!/usr/bin/env bash

# Ensures the script is not running as sudo or root

CURRENTUSER=$(whoami)

if [[ $CURRENTUSER == "root" ]]; then
  echo "Do not run this script as root/sudo"
  exit
fi

# attempts to gain sudo access if not already accquired

sudo -v

# exits the script if sudo access is not granted
sudo -n true 2>/dev/null || {
  echo "You must have the ability to run sudo commands to execute this script"
  exit 1
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

# set up nvm to run in current terminal
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# configure nvm
nvm install --lts
nvm use --lts
nvm alias default 'lts/*'
source $HOME/.bashrc

# add npm globals bin to path
NPMBIN="$(npm config get prefix)/bin"
LINETOADD='export PATH="$PATH:'"$NPMBIN"'"'

grep -qxF "$LINETOADD" "$HOME/.bashrc" || echo "$LINETOADD" >>"$HOME/.bashrc"
