#!/usr/bin/env bash

# Ensures the script is not running as sudo or root

CURRENTUSER=$(whoami)

if [[ $CURRENTUSER == "root" ]]; then
  echo "Do not run this script as root/sudo"
  exit
fi

# attempts to gain sudo access if not already accquired

sudo -v

# exits the script if sudo access is not granted
sudo -n true 2>/dev/null || {
  echo "You must have the ability to run sudo commands to execute this script"
  exit 1
}

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

#### install required APT packaged

# update and install c build tools
# sudo apt update -y && sudo apt install -y
#
sudo apt update -y && sudo apt install git curl wget ninja-build \
  gettext cmake unzip build-essential libtool libtool-bin autoconf \
  automake pkg-config doxygen -y
