#!/usr/bin/env bash

git clone https://github.com/neovim/neovim.git ~/.builds/neovim
cd ~/.builds/neovim || exit
git fetch
git checkout v0.11.2

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
