#!/usr/bin/env bash
XDG_CONFIG_HOME=$HOME/.config

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "--------- dev-env ---------"

cd "$script_dir" || exit
copy_dir() {

  from=$1
  to=$2

  pushd "$from" >/dev/null || exit
  cdirs=$(find . -maxdepth 1 -mindepth 1 -type d)

  for cdir in $cdirs; do
    execute rm -rf "$to/$cdir"
    execute cp -r "$cdir" "$to/$cdir"
  done

  popd >/dev/null || exit
}

# copy_dir .config $XDG_CONFIG_HOME
# copy_dir .local $HOME/.local

copy_file() {

  from=$1
  to=$2

  cfiles=$(find "$from" -maxdepth 1 -mindepth 1 -type f -printf '%f\n')

  for cfile in $cfiles; do
    execute rm -f "$to/$cfile"
    execute cp "$from/$cfile" "$to/$cfile"
  done
}

copy_file ./home "$HOME"

# copy_file . "$HOME"
